# Generated by Django 3.0.3 on 2020-04-20 18:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Геолокация', 'verbose_name_plural': 'Геолокации'},
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('starts_working', models.TimeField(default=datetime.time(9, 0))),
                ('finishes_working', models.TimeField(default=datetime.time(22, 0))),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magazine.Location')),
            ],
        ),
    ]
