# Generated by Django 3.0.3 on 2020-04-16 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('Курьер', 'Курьер'), ('Пользователь', 'Пользователь')], default='Пользователь', max_length=30),
        ),
    ]
