# Generated by Django 3.0.3 on 2020-03-08 22:21

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default='default.png', upload_to='uploads'),
            preserve_default=False,
        ),
    ]
