# Generated by Django 3.0.3 on 2020-04-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0002_profile_type_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='busy',
            field=models.BooleanField(default=False),
        ),
    ]
