# Generated by Django 3.0.3 on 2020-04-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20200427_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='client',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AlterField(
            model_name='location',
            name='title',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='RoomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.ManyToManyField(blank=True, to='magazine.Location')),
                ('participants', models.ManyToManyField(blank=True, related_name='room', to='magazine.Profile')),
            ],
        ),
    ]
