# Generated by Django 3.0.3 on 2020-04-16 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_profile_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='type_user',
        ),
        migrations.AddField(
            model_name='profile',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_as_driver', to='magazine.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_as_passenger', to='magazine.Profile'),
        ),
    ]
