# Generated by Django 3.0.3 on 2020-03-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_auto_20200325_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Продукт корзины', 'verbose_name_plural': 'Продукты корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='typeproduct',
            options={'verbose_name': 'Тип продукта', 'verbose_name_plural': 'Тип продуктов'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_total',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
