# Generated by Django 3.0.3 on 2020-03-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20200326_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
