# Generated by Django 3.0.3 on 2020-04-16 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0004_auto_20200416_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='passenger',
        ),
        migrations.AddField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_as_client', to='magazine.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='courier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_as_courier', to='magazine.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
