# Generated by Django 3.0.3 on 2020-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0005_auto_20200428_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Принят к обработке', 'Принят к обработке'), ('Выполняется', 'Выполняется'), ('Оплачен', 'Оплачен')], default='Принят к обработке', max_length=30),
        ),
    ]
