# Generated by Django 3.0.3 on 2020-05-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0006_auto_20200513_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='personal',
            field=models.ManyToManyField(to='magazine.Profile'),
        ),
    ]
