export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_UPDATE_TOKEN = "AUTH_UPDATE_TOKEN";
export const AUTH_DONE_REFRESHING_TOKEN = "AUTH_DONE_REFRESHING_TOKEN";
export const AUTH_REFRESHING_TOKEN = "AUTH_REFRESHING_TOKEN";
export const AUTH_SAVE_TOKEN = "AUTH_SAVE_TOKEN"
export const CART_START = "CART_START";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAIL = "CART_FAIL";
export const ADD_LOCATION = "ADD_LOCATION";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";




