// AUTH actions types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_UPDATE_TOKEN = "AUTH_UPDATE_TOKEN";
export const AUTH_DONE_REFRESHING_TOKEN = "AUTH_DONE_REFRESHING_TOKEN";
export const AUTH_REFRESHING_TOKEN = "AUTH_REFRESHING_TOKEN";
export const AUTH_SAVE_TOKEN = "AUTH_SAVE_TOKEN"

export const REQUEST_CART = "REQUEST_CART";
export const SUCCESS_CART = "SUCCESS_CART";
export const FAILURE_CART = "FAILURE_CART";

export const ADD_LOCATION = "ADD_LOCATION";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const GET_ROOM_SUCCESS = "GET_ROOM_SUCCESS";

export const REQUEST_BUYING = "REQUEST_BUYING";
export const SUCCESS_BUYING = "SUCCESS_BUYING";
export const FAILURE_BUYING = "FAILURE_BUYING";

export const REQUEST_REMOVE_FROM_CART = "REQUEST_REMOVE_FROM_CART";
export const SUCCESS_REMOVE_FROM_CART = "SUCCESS_REMOVE_FROM_CART";
export const FAILURE_REMOVE_FROM_CART = "FAILURE_REMOVE_FROM_CART";

export const REQUEST_UPDATE_PRODUCT_IN_CART = "REQUEST_UPDATE_PRODUCT_IN_CART";
export const SUCCESS_UPDATE_PRODUCT_IN_CART = "SUCCESS_UPDATE_PRODUCT_IN_CART";
export const FAILURE_UPDATE_PRODUCT_IN_CART = "FAILURE_UPDATE_PRODUCT_IN_CART";

export const REQUEST_FETCH_PRODUCT = "REQUEST_FETCH_PRODUCT";
export const SUCCESS_FETCH_PRODUCT = "SUCCESS_FETCH_PRODUCT";
export const FAILURE_FETCH_PRODUCT = "FAILURE_FETCH_PRODUCT";




